cinemaweb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve as mediaserve
from django.conf.urls import url
from django.views.static import serve

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('categories.urls')),
    path('', include('home.urls')),
    path('', include('movies.urls')),
    path('', include('users.urls')),
    path ('accounts/', include('allauth.urls')),
]

home/urls.py
from django.urls import path 
from home.views import index, about, avtor,contakt
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

app_name = "home"

urlpatterns = [
    path('', index, name = "index"),
    path('about/', about, name = "about"),
    path('avtor/', avtor, name = "avtor"),
    path('contakt/', contakt, name = "contakt"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path 
from django.conf.urls.static import static
from users.views import register, user_login
from django.conf import settings

app_name = "users"
print("fsdfsd")

urlpatterns = [
    path('register/', register, name = "register"),
    path('login/', user_login, name='user_login'),
]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from email.mime import image
from django.db import models
 

class Setting(models.Model):
    title = models.CharField(max_length=250)
    decription = models.TextField()
    logo = models.ImageField(upload_to = 'logo/')
    tel = models.CharField(max_length=255)
    facebook = models.CharField(max_length=255)
    twitter = models.CharField(max_length=255)
    google = models.CharField(max_length=255)

    def __str__(self):
        return self.title 

    class Meta:
        verbose_name = "Настройка"
        verbose_name_plural = "Настройки"

class About(models.Model):
    description = models.TextField()
    image_about = models.ImageField(upload_to = "about/")

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = "О нас"
        verbose_name_plural = "О нас"

home/views.py
from django.shortcuts import render
from home.models import About, Setting
from movies.models import Movie, MovieComment
from categories.models import Category
from django.apps import apps
# Create your views here.

def index(request):
    # print(apps.get_app_config('app_label').path)
    home = Setting.objects.latest('id')
    slide_movies = Movie.objects.all().order_by('-id')[:5]
    movies = Movie.objects.all().order_by('-id')[:8]
    one_random_movie = Movie.objects.all().order_by('?')
    one_random_genre = Movie.objects.all().order_by('?')[:1]
    categories = Category.objects.all().order_by('-id')
    most_popular_movie = Movie.objects.all().order_by('-genre')
    comments = MovieComment.objects.all().order_by('-id')
    context = {
        'home' : home,
        'movies' : movies,
        'slide_movies' : slide_movies,
        'one_random_movie' : one_random_movie,
        'one_random_genre' : one_random_genre,
        'categories' : categories,
        'most_popular_movie' : most_popular_movie,
        'comments' : comments,

    }
    return render(request, 'home/index.html', context)

def about(request):
    home = Setting.objects.latest('-id')
    about = About.objects.latest('id')
    context = {
        'home' : home,
        'about' : about, 
    }

    return render(request, 'home/about_us.html', context)

def avtor(request):
    home = Setting.objects.latest('-id')
    about = About.objects.latest('id')
    context = {
        'home' : home,
        'about' : about, 
    }

    return render(request, 'home/about_me.html', context)

def contakt(request):
    home = Setting.objects.latest('-id')
    about = About.objects.latest('id')
    context = {
        'home' : home,
        'about' : about, 
    }

    return render(request, 'home/contakt.html', context)

home/templates/home/include/footer.html
{% load static %}
<!-- footer section-->
<footer class="ht-footer">
	<div class="container">
		<div class="flex-parent-ft">
			<div class="flex-child-ft item1">
				 <a href="index.html"><img class="logo" src="{% static 'home/images/logo1.png' %}" alt=""></a>
				 <p>Соц. Сети: </p>
				 <div class="social-link">
					<a href="{{ home.facebook }}"><i><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
						<path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
					  </svg></i></a>
					<a href="{{ home.twitter }}"><i><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
						<path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
					  </svg></i></a>
					<a href="{{ home.instagram }}"><i><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
						<path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
					  </svg></i></a>
					<a href="{{ home.youtube }}"><i><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-youtube" viewBox="0 0 16 16">
						<path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"/>
					  </svg></i></a>
				</div>
				 <p>Минск<br>
				Улица "главный бульвар" д. 11</p>
				<p>Позвоните нам: <a href="#">+375 29 666 66 66</a></p>
			</div>
			<div class="flex-child-ft item2">
				<h4>Ресурсы</h4>
				<ul>
					<li><a href="{% url 'home:avtor' %}">Об авторе</a></li> 
					<li><a href="#">Блокбастер</a></li>
					<li><a href="{% url 'home:contakt' %}">Контакты</a></li>
					<li><a href="#">Форум</a></li>
					<li><a href="#">Блог</a></li>
					<li><a href="#">Помощь</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item3">
				<h4>Условия</h4>
				<ul>
					<li><a href="#">Условия использования</a></li> 
					<li><a href="#">Политика конфиде-сти</a></li>	
					<li><a href="#">Безопасность</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item4">
				<h4>Аккаунт</h4>
				<ul>
					<li><a href="#">Мой аккаунт</a></li> 
					<li><a href="#">Список просмотреного</a></li>	
					<li><a href="#">Коллекции</a></li>
					<li><a href="#">Гид пользователя</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item5">
				<h4>Новостная рассылка</h4>
				<p>Подпишитесь на нашу систему рассылки новостей прямо сейчас <br> чтобы получать последние новости от нас.</p>
				<form action="#">
					<input type="text" placeholder="Введите ваш email...">
				</form>
				<a href="#" class="btn">Подпишитесь сейчас <i class="ion-ios-arrow-forward"></i></a>
			</div>
		</div>
	</div>
	<div class="ft-copyright">
		<div class="ft-left">
			<p>© 2022 Azmovl. Все права защищены. Создатель Amid.</p>
		</div>
		<div class="backtotop">
			<p><a href="#" id="back-to-top">Наверх  <i class="ion-ios-arrow-thin-up"></i></a></p>
		</div>
	</div>
</footer>
<!-- end of footer section-->

home/templates/home/include/header.html
{% load static %}
<!-- BEGIN | Header -->
<header class="ht-header">
	<div class="container">
		<nav class="navbar navbar-default navbar-custom">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header logo">
				    <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					    <span class="sr-only">Toggle navigation</span>
					    <div id="nav-icon1">
							<span></span>
							<span></span>
							<span></span>
						</div>
				    </div>
				    <a href="{% url 'index' %}"><img class="logo" src="{% static 'home/images/logo1.png' %}" alt="" width="119" height="58"></a>
			    </div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav flex-child-menu menu-left">
						<li class="hidden">
							<a href="#page-top"></a>
						</li>
						<li class="dropdown first">
							<a href="{% url 'index' %}" >
							Домой 
							</a>
							 
						</li>
						<li class="dropdown first">
							<a class="btn btn-default dropdown-toggle lv1" data-toggle="dropdown" data-hover="dropdown">
							Жанры
							</a>
						</li>
						<li class="dropdown first">
							<a href="{% url 'home:about' %}">
							О нас 
							</a>
						</li>
						<li><a href="#">Связаться с нами</a></li>
					</ul> 
					<ul class="nav navbar-nav flex-child-menu menu-right">  
						<li><a href="{% url 'users:user_login' %}">Логин</a></li>
						<li><a href="{% url 'users:register' %}">Зарегистрироваться</a></li>
					</ul>
				</div>
			<!-- /.navbar-collapse -->
	    </nav>
	    
	    <!-- top search form -->
	    <!-- <div class="top-search">
	    	<select>
				<option value="united">TV show</option>
				<option value="saab">Others</option>
			</select>
			<input type="text" name="key" placeholder=" Введите названия фильма">
	    </div> -->
		<form action="{% url 'movie_search' %}" method="GET">
			<div class="bg-light rounded rounded-pill shadow-sm">
				<div class="top-search">
					<!-- <input type="search" name="query" placeholder="Поиск..." aria-describedby="button-addon1" class="form-control border-0 bg-light"> -->
					<input type="search" name="key" placeholder=" Введите названия фильма">
				</div>
			</div>
		</form>
	</div>
</header>
<!-- END | Header -->